#:schema node_modules/wrangler/config-schema.json
name = "unifi-cloudflare-ddns-access"
main = "src/index.ts"
compatibility_date = "2025-02-16"
compatibility_flags = ["nodejs_compat"]

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true
logs.enabled = true

# Automatically place your workloads in an optimal location to minimize latency.
# Docs: https://developers.cloudflare.com/workers/configuration/smart-placement/#smart-placement
[placement]
mode = "smart"

# echo'd out during deployment to dynamically set binding's id to secret
# [[kv_namespaces]]
# binding = "unifi_cloudflare_ddns_access_kv"
# id = "${CLOUDFLARE_NAMESPACE_ID}"
